#Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.parallel=true
kotlin.parallel.compilation.enabled=true

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4G
kotlin.native.binary.gc=cms
kotlin.incremental.wasm=true

#MPP
kotlin.mpp.enableCInteropCommonization=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#Experimental
org.jetbrains.compose.experimental.jscanvas.enabled=true
org.jetbrains.compose.experimental.macos.enabled=true

#Maven publishing (vanniktech defaults, inherited by all submodules)
GROUP=io.github.shivathapaa
VERSION_NAME=3.0.0

POM_INCEPTION_YEAR=2024
POM_URL=https://github.com/shivathapaa/Nepali-Date-Picker

POM_LICENSE_NAME=MPL 2.0
POM_LICENSE_URL=https://github.com/shivathapaa/Nepali-Date-Picker/blob/main/LICENSE
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=shivathapaa
POM_DEVELOPER_NAME=Shiva Thapa
POM_DEVELOPER_EMAIL=query.shivathapaa.dev@gmail.com
POM_DEVELOPER_URL=https://github.com/shivathapaa/

POM_SCM_URL=https://github.com/shivathapaa/Nepali-Date-Picker
POM_SCM_CONNECTION=scm:git:git://github.com/shivathapaa/Nepali-Date-Picker.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/shivathapaa/Nepali-Date-Picker.git