// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum LangDto {
  english,
  nepali;
}

enum NameFormatDto {
  full,
  medium,
  short;
}

enum DateFormatStyleDto {
  full,
  long,
  medium,
  shortMdy,
  shortYmd,
  compactMdy,
  compactYmd;
}

enum DigitScriptDto {
  latin,
  devanagari;
}

enum EventKindDto {
  governmentPublic,
  religious,
  regional,
  observance;
}

enum DatePatternDto {
  yyyySlashMmSlashDd,
  yyyyDashMmDashDd,
  ddSlashMmSlashYyyy,
  ddDashMmDashYyyy;
}

enum BrightnessDto {
  system,
  light,
  dark;
}

/// A plain year, month and day in whichever calendar the call documents.
class DateDto {
  DateDto({
    required this.year,
    required this.month,
    required this.dayOfMonth,
  });

  int year;

  int month;

  int dayOfMonth;

  List<Object?> _toList() {
    return <Object?>[
      year,
      month,
      dayOfMonth,
    ];
  }

  Object encode() {
    return _toList();  }

  static DateDto decode(Object result) {
    result as List<Object?>;
    return DateDto(
      year: result[0]! as int,
      month: result[1]! as int,
      dayOfMonth: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DateDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(year, other.year) && _deepEquals(month, other.month) && _deepEquals(dayOfMonth, other.dayOfMonth);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DateDto(year: $year, month: $month, dayOfMonth: $dayOfMonth)';
  }
}

/// A wall-clock time of day in the Asia/Kathmandu zone.
class TimeDto {
  TimeDto({
    required this.hour,
    required this.minute,
    required this.second,
    required this.nanosecond,
  });

  int hour;

  int minute;

  int second;

  int nanosecond;

  List<Object?> _toList() {
    return <Object?>[
      hour,
      minute,
      second,
      nanosecond,
    ];
  }

  Object encode() {
    return _toList();  }

  static TimeDto decode(Object result) {
    result as List<Object?>;
    return TimeDto(
      hour: result[0]! as int,
      minute: result[1]! as int,
      second: result[2]! as int,
      nanosecond: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TimeDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hour, other.hour) && _deepEquals(minute, other.minute) && _deepEquals(second, other.second) && _deepEquals(nanosecond, other.nanosecond);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TimeDto(hour: $hour, minute: $minute, second: $second, nanosecond: $nanosecond)';
  }
}

/// The shared `CustomCalendar`: a fully described date. Fields the producing
/// call does not compute hold -1.
class CalendarDto {
  CalendarDto({
    required this.year,
    required this.month,
    required this.dayOfMonth,
    required this.era,
    required this.firstDayOfMonth,
    required this.lastDayOfMonth,
    required this.totalDaysInMonth,
    required this.dayOfWeekInMonth,
    required this.dayOfWeek,
    required this.dayOfYear,
    required this.weekOfMonth,
    required this.weekOfYear,
  });

  int year;

  int month;

  int dayOfMonth;

  int era;

  int firstDayOfMonth;

  int lastDayOfMonth;

  int totalDaysInMonth;

  int dayOfWeekInMonth;

  int dayOfWeek;

  int dayOfYear;

  int weekOfMonth;

  int weekOfYear;

  List<Object?> _toList() {
    return <Object?>[
      year,
      month,
      dayOfMonth,
      era,
      firstDayOfMonth,
      lastDayOfMonth,
      totalDaysInMonth,
      dayOfWeekInMonth,
      dayOfWeek,
      dayOfYear,
      weekOfMonth,
      weekOfYear,
    ];
  }

  Object encode() {
    return _toList();  }

  static CalendarDto decode(Object result) {
    result as List<Object?>;
    return CalendarDto(
      year: result[0]! as int,
      month: result[1]! as int,
      dayOfMonth: result[2]! as int,
      era: result[3]! as int,
      firstDayOfMonth: result[4]! as int,
      lastDayOfMonth: result[5]! as int,
      totalDaysInMonth: result[6]! as int,
      dayOfWeekInMonth: result[7]! as int,
      dayOfWeek: result[8]! as int,
      dayOfYear: result[9]! as int,
      weekOfMonth: result[10]! as int,
      weekOfYear: result[11]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CalendarDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(year, other.year) && _deepEquals(month, other.month) && _deepEquals(dayOfMonth, other.dayOfMonth) && _deepEquals(era, other.era) && _deepEquals(firstDayOfMonth, other.firstDayOfMonth) && _deepEquals(lastDayOfMonth, other.lastDayOfMonth) && _deepEquals(totalDaysInMonth, other.totalDaysInMonth) && _deepEquals(dayOfWeekInMonth, other.dayOfWeekInMonth) && _deepEquals(dayOfWeek, other.dayOfWeek) && _deepEquals(dayOfYear, other.dayOfYear) && _deepEquals(weekOfMonth, other.weekOfMonth) && _deepEquals(weekOfYear, other.weekOfYear);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CalendarDto(year: $year, month: $month, dayOfMonth: $dayOfMonth, era: $era, firstDayOfMonth: $firstDayOfMonth, lastDayOfMonth: $lastDayOfMonth, totalDaysInMonth: $totalDaysInMonth, dayOfWeekInMonth: $dayOfWeekInMonth, dayOfWeek: $dayOfWeek, dayOfYear: $dayOfYear, weekOfMonth: $weekOfMonth, weekOfYear: $weekOfYear)';
  }
}

/// Month-grid metadata for either calendar system.
class MonthInfoDto {
  MonthInfoDto({
    required this.year,
    required this.month,
    required this.totalDaysInMonth,
    required this.firstDayOfMonth,
    required this.lastDayOfMonth,
    required this.daysFromStartOfWeekToFirstOfMonth,
  });

  int year;

  int month;

  int totalDaysInMonth;

  int firstDayOfMonth;

  int lastDayOfMonth;

  int daysFromStartOfWeekToFirstOfMonth;

  List<Object?> _toList() {
    return <Object?>[
      year,
      month,
      totalDaysInMonth,
      firstDayOfMonth,
      lastDayOfMonth,
      daysFromStartOfWeekToFirstOfMonth,
    ];
  }

  Object encode() {
    return _toList();  }

  static MonthInfoDto decode(Object result) {
    result as List<Object?>;
    return MonthInfoDto(
      year: result[0]! as int,
      month: result[1]! as int,
      totalDaysInMonth: result[2]! as int,
      firstDayOfMonth: result[3]! as int,
      lastDayOfMonth: result[4]! as int,
      daysFromStartOfWeekToFirstOfMonth: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MonthInfoDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(year, other.year) && _deepEquals(month, other.month) && _deepEquals(totalDaysInMonth, other.totalDaysInMonth) && _deepEquals(firstDayOfMonth, other.firstDayOfMonth) && _deepEquals(lastDayOfMonth, other.lastDayOfMonth) && _deepEquals(daysFromStartOfWeekToFirstOfMonth, other.daysFromStartOfWeekToFirstOfMonth);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MonthInfoDto(year: $year, month: $month, totalDaysInMonth: $totalDaysInMonth, firstDayOfMonth: $firstDayOfMonth, lastDayOfMonth: $lastDayOfMonth, daysFromStartOfWeekToFirstOfMonth: $daysFromStartOfWeekToFirstOfMonth)';
  }
}

/// A calendar paired with a time of day.
class DateTimeDto {
  DateTimeDto({
    required this.calendar,
    required this.time,
  });

  CalendarDto calendar;

  TimeDto time;

  List<Object?> _toList() {
    return <Object?>[
      calendar,
      time,
    ];
  }

  Object encode() {
    return _toList();  }

  static DateTimeDto decode(Object result) {
    result as List<Object?>;
    return DateTimeDto(
      calendar: result[0]! as CalendarDto,
      time: result[1]! as TimeDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DateTimeDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(calendar, other.calendar) && _deepEquals(time, other.time);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DateTimeDto(calendar: $calendar, time: $time)';
  }
}

/// An inclusive year range.
class YearRangeDto {
  YearRangeDto({
    required this.first,
    required this.last,
  });

  int first;

  int last;

  List<Object?> _toList() {
    return <Object?>[
      first,
      last,
    ];
  }

  Object encode() {
    return _toList();  }

  static YearRangeDto decode(Object result) {
    result as List<Object?>;
    return YearRangeDto(
      first: result[0]! as int,
      last: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YearRangeDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(first, other.first) && _deepEquals(last, other.last);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'YearRangeDto(first: $first, last: $last)';
  }
}

/// How dates render: language, preset style, name lengths and digit script.
/// A null [digitScript] follows the language.
class LocaleDto {
  LocaleDto({
    required this.language,
    required this.dateFormat,
    required this.weekDayName,
    required this.monthName,
    this.digitScript,
  });

  LangDto language;

  DateFormatStyleDto dateFormat;

  NameFormatDto weekDayName;

  NameFormatDto monthName;

  DigitScriptDto? digitScript;

  List<Object?> _toList() {
    return <Object?>[
      language,
      dateFormat,
      weekDayName,
      monthName,
      digitScript,
    ];
  }

  Object encode() {
    return _toList();  }

  static LocaleDto decode(Object result) {
    result as List<Object?>;
    return LocaleDto(
      language: result[0]! as LangDto,
      dateFormat: result[1]! as DateFormatStyleDto,
      weekDayName: result[2]! as NameFormatDto,
      monthName: result[3]! as NameFormatDto,
      digitScript: result[4] as DigitScriptDto?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocaleDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(language, other.language) && _deepEquals(dateFormat, other.dateFormat) && _deepEquals(weekDayName, other.weekDayName) && _deepEquals(monthName, other.monthName) && _deepEquals(digitScript, other.digitScript);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LocaleDto(language: $language, dateFormat: $dateFormat, weekDayName: $weekDayName, monthName: $monthName, digitScript: $digitScript)';
  }
}

/// One thing on one Bikram Sambat day.
class EventDto {
  EventDto({
    required this.year,
    required this.month,
    required this.dayOfMonth,
    required this.name,
    required this.kind,
    required this.closesOffices,
    this.id,
    this.payload,
  });

  int year;

  int month;

  int dayOfMonth;

  String name;

  EventKindDto kind;

  bool closesOffices;

  String? id;

  String? payload;

  List<Object?> _toList() {
    return <Object?>[
      year,
      month,
      dayOfMonth,
      name,
      kind,
      closesOffices,
      id,
      payload,
    ];
  }

  Object encode() {
    return _toList();  }

  static EventDto decode(Object result) {
    result as List<Object?>;
    return EventDto(
      year: result[0]! as int,
      month: result[1]! as int,
      dayOfMonth: result[2]! as int,
      name: result[3]! as String,
      kind: result[4]! as EventKindDto,
      closesOffices: result[5]! as bool,
      id: result[6] as String?,
      payload: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EventDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(year, other.year) && _deepEquals(month, other.month) && _deepEquals(dayOfMonth, other.dayOfMonth) && _deepEquals(name, other.name) && _deepEquals(kind, other.kind) && _deepEquals(closesOffices, other.closesOffices) && _deepEquals(id, other.id) && _deepEquals(payload, other.payload);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EventDto(year: $year, month: $month, dayOfMonth: $dayOfMonth, name: $name, kind: $kind, closesOffices: $closesOffices, id: $id, payload: $payload)';
  }
}

/// One institution's closed days: the weekdays it never opens plus the
/// holidays it keeps, sent as data with every policy call.
class PolicyDto {
  PolicyDto({
    required this.weeklyOffDays,
    required this.events,
  });

  List<int> weeklyOffDays;

  List<EventDto> events;

  List<Object?> _toList() {
    return <Object?>[
      weeklyOffDays,
      events,
    ];
  }

  Object encode() {
    return _toList();  }

  static PolicyDto decode(Object result) {
    result as List<Object?>;
    return PolicyDto(
      weeklyOffDays: (result[0]! as List<Object?>).cast<int>(),
      events: (result[1]! as List<Object?>).cast<EventDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PolicyDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(weeklyOffDays, other.weeklyOffDays) && _deepEquals(events, other.events);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PolicyDto(weeklyOffDays: $weeklyOffDays, events: $events)';
  }
}

/// What one day is under a policy.
class DayStatusDto {
  DayStatusDto({
    required this.isWeeklyOff,
    required this.isNonWorking,
    this.primaryKind,
    required this.names,
    required this.events,
    required this.closures,
  });

  bool isWeeklyOff;

  bool isNonWorking;

  EventKindDto? primaryKind;

  List<String> names;

  List<EventDto> events;

  List<EventDto> closures;

  List<Object?> _toList() {
    return <Object?>[
      isWeeklyOff,
      isNonWorking,
      primaryKind,
      names,
      events,
      closures,
    ];
  }

  Object encode() {
    return _toList();  }

  static DayStatusDto decode(Object result) {
    result as List<Object?>;
    return DayStatusDto(
      isWeeklyOff: result[0]! as bool,
      isNonWorking: result[1]! as bool,
      primaryKind: result[2] as EventKindDto?,
      names: (result[3]! as List<Object?>).cast<String>(),
      events: (result[4]! as List<Object?>).cast<EventDto>(),
      closures: (result[5]! as List<Object?>).cast<EventDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DayStatusDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isWeeklyOff, other.isWeeklyOff) && _deepEquals(isNonWorking, other.isNonWorking) && _deepEquals(primaryKind, other.primaryKind) && _deepEquals(names, other.names) && _deepEquals(events, other.events) && _deepEquals(closures, other.closures);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DayStatusDto(isWeeklyOff: $isWeeklyOff, isNonWorking: $isNonWorking, primaryKind: $primaryKind, names: $names, events: $events, closures: $closures)';
  }
}

/// The three date-bound selectable rules the engine ships, plus the policy
/// decorators. Custom predicates cannot cross the bridge.
class SelectableDto {
  SelectableDto({
    this.minDate,
    this.maxDate,
    required this.includeMinDate,
    required this.includeMaxDate,
    this.excludeWeekend,
    this.excludeClosuresOf,
  });

  /// Dates before this are refused; alone it means "this date and later".
  DateDto? minDate;

  /// Dates after this are refused; alone it means "this date and earlier".
  DateDto? maxDate;

  bool includeMinDate;

  bool includeMaxDate;

  /// Weekdays to refuse, 1 for Sunday through 7 for Saturday.
  List<int>? excludeWeekend;

  /// Refuse days this policy's events close.
  PolicyDto? excludeClosuresOf;

  List<Object?> _toList() {
    return <Object?>[
      minDate,
      maxDate,
      includeMinDate,
      includeMaxDate,
      excludeWeekend,
      excludeClosuresOf,
    ];
  }

  Object encode() {
    return _toList();  }

  static SelectableDto decode(Object result) {
    result as List<Object?>;
    return SelectableDto(
      minDate: result[0] as DateDto?,
      maxDate: result[1] as DateDto?,
      includeMinDate: result[2]! as bool,
      includeMaxDate: result[3]! as bool,
      excludeWeekend: (result[4] as List<Object?>?)?.cast<int>(),
      excludeClosuresOf: result[5] as PolicyDto?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SelectableDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(minDate, other.minDate) && _deepEquals(maxDate, other.maxDate) && _deepEquals(includeMinDate, other.includeMinDate) && _deepEquals(includeMaxDate, other.includeMaxDate) && _deepEquals(excludeWeekend, other.excludeWeekend) && _deepEquals(excludeClosuresOf, other.excludeClosuresOf);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SelectableDto(minDate: $minDate, maxDate: $maxDate, includeMinDate: $includeMinDate, includeMaxDate: $includeMaxDate, excludeWeekend: $excludeWeekend, excludeClosuresOf: $excludeClosuresOf)';
  }
}

/// Every slot of the appearance proxy; `0` keeps Material's own value.
class AppearanceDto {
  AppearanceDto({
    required this.brightness,
    required this.primaryArgb,
    required this.onPrimaryArgb,
    required this.primaryContainerArgb,
    required this.onPrimaryContainerArgb,
    required this.secondaryContainerArgb,
    required this.onSecondaryContainerArgb,
    required this.surfaceArgb,
    required this.onSurfaceArgb,
    required this.surfaceVariantArgb,
    required this.onSurfaceVariantArgb,
    required this.outlineArgb,
  });

  BrightnessDto brightness;

  int primaryArgb;

  int onPrimaryArgb;

  int primaryContainerArgb;

  int onPrimaryContainerArgb;

  int secondaryContainerArgb;

  int onSecondaryContainerArgb;

  int surfaceArgb;

  int onSurfaceArgb;

  int surfaceVariantArgb;

  int onSurfaceVariantArgb;

  int outlineArgb;

  List<Object?> _toList() {
    return <Object?>[
      brightness,
      primaryArgb,
      onPrimaryArgb,
      primaryContainerArgb,
      onPrimaryContainerArgb,
      secondaryContainerArgb,
      onSecondaryContainerArgb,
      surfaceArgb,
      onSurfaceArgb,
      surfaceVariantArgb,
      onSurfaceVariantArgb,
      outlineArgb,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppearanceDto decode(Object result) {
    result as List<Object?>;
    return AppearanceDto(
      brightness: result[0]! as BrightnessDto,
      primaryArgb: result[1]! as int,
      onPrimaryArgb: result[2]! as int,
      primaryContainerArgb: result[3]! as int,
      onPrimaryContainerArgb: result[4]! as int,
      secondaryContainerArgb: result[5]! as int,
      onSecondaryContainerArgb: result[6]! as int,
      surfaceArgb: result[7]! as int,
      onSurfaceArgb: result[8]! as int,
      surfaceVariantArgb: result[9]! as int,
      onSurfaceVariantArgb: result[10]! as int,
      outlineArgb: result[11]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppearanceDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(brightness, other.brightness) && _deepEquals(primaryArgb, other.primaryArgb) && _deepEquals(onPrimaryArgb, other.onPrimaryArgb) && _deepEquals(primaryContainerArgb, other.primaryContainerArgb) && _deepEquals(onPrimaryContainerArgb, other.onPrimaryContainerArgb) && _deepEquals(secondaryContainerArgb, other.secondaryContainerArgb) && _deepEquals(onSecondaryContainerArgb, other.onSecondaryContainerArgb) && _deepEquals(surfaceArgb, other.surfaceArgb) && _deepEquals(onSurfaceArgb, other.onSurfaceArgb) && _deepEquals(surfaceVariantArgb, other.surfaceVariantArgb) && _deepEquals(onSurfaceVariantArgb, other.onSurfaceVariantArgb) && _deepEquals(outlineArgb, other.outlineArgb);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppearanceDto(brightness: $brightness, primaryArgb: $primaryArgb, onPrimaryArgb: $onPrimaryArgb, primaryContainerArgb: $primaryContainerArgb, onPrimaryContainerArgb: $onPrimaryContainerArgb, secondaryContainerArgb: $secondaryContainerArgb, onSecondaryContainerArgb: $onSecondaryContainerArgb, surfaceArgb: $surfaceArgb, onSurfaceArgb: $onSurfaceArgb, surfaceVariantArgb: $surfaceVariantArgb, onSurfaceVariantArgb: $onSurfaceVariantArgb, outlineArgb: $outlineArgb)';
  }
}

/// Everything a modal picker dialog needs. Field meanings mirror the View and
/// ViewController factories.
class DialogConfigDto {
  DialogConfigDto({
    this.initialSelectedDate,
    required this.locale,
    required this.yearRangeStart,
    required this.yearRangeEnd,
    this.selectable,
    required this.showModeToggle,
    required this.showTodayButton,
    required this.showEnglishDate,
    this.englishDateLocale,
    required this.initialCalendarSystemEra,
    required this.showCalendarSystemToggle,
    required this.showAdjacentMonthDays,
    this.eventOptions,
    this.title,
    required this.confirmText,
    required this.dismissText,
    required this.tonalElevation,
    required this.cornerRadius,
  });

  DateDto? initialSelectedDate;

  LocaleDto locale;

  int yearRangeStart;

  int yearRangeEnd;

  SelectableDto? selectable;

  bool showModeToggle;

  bool showTodayButton;

  bool showEnglishDate;

  LocaleDto? englishDateLocale;

  int initialCalendarSystemEra;

  bool showCalendarSystemToggle;

  bool showAdjacentMonthDays;

  EventOptionsDto? eventOptions;

  String? title;

  String confirmText;

  String dismissText;

  double tonalElevation;

  double cornerRadius;

  List<Object?> _toList() {
    return <Object?>[
      initialSelectedDate,
      locale,
      yearRangeStart,
      yearRangeEnd,
      selectable,
      showModeToggle,
      showTodayButton,
      showEnglishDate,
      englishDateLocale,
      initialCalendarSystemEra,
      showCalendarSystemToggle,
      showAdjacentMonthDays,
      eventOptions,
      title,
      confirmText,
      dismissText,
      tonalElevation,
      cornerRadius,
    ];
  }

  Object encode() {
    return _toList();  }

  static DialogConfigDto decode(Object result) {
    result as List<Object?>;
    return DialogConfigDto(
      initialSelectedDate: result[0] as DateDto?,
      locale: result[1]! as LocaleDto,
      yearRangeStart: result[2]! as int,
      yearRangeEnd: result[3]! as int,
      selectable: result[4] as SelectableDto?,
      showModeToggle: result[5]! as bool,
      showTodayButton: result[6]! as bool,
      showEnglishDate: result[7]! as bool,
      englishDateLocale: result[8] as LocaleDto?,
      initialCalendarSystemEra: result[9]! as int,
      showCalendarSystemToggle: result[10]! as bool,
      showAdjacentMonthDays: result[11]! as bool,
      eventOptions: result[12] as EventOptionsDto?,
      title: result[13] as String?,
      confirmText: result[14]! as String,
      dismissText: result[15]! as String,
      tonalElevation: result[16]! as double,
      cornerRadius: result[17]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DialogConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(initialSelectedDate, other.initialSelectedDate) && _deepEquals(locale, other.locale) && _deepEquals(yearRangeStart, other.yearRangeStart) && _deepEquals(yearRangeEnd, other.yearRangeEnd) && _deepEquals(selectable, other.selectable) && _deepEquals(showModeToggle, other.showModeToggle) && _deepEquals(showTodayButton, other.showTodayButton) && _deepEquals(showEnglishDate, other.showEnglishDate) && _deepEquals(englishDateLocale, other.englishDateLocale) && _deepEquals(initialCalendarSystemEra, other.initialCalendarSystemEra) && _deepEquals(showCalendarSystemToggle, other.showCalendarSystemToggle) && _deepEquals(showAdjacentMonthDays, other.showAdjacentMonthDays) && _deepEquals(eventOptions, other.eventOptions) && _deepEquals(title, other.title) && _deepEquals(confirmText, other.confirmText) && _deepEquals(dismissText, other.dismissText) && _deepEquals(tonalElevation, other.tonalElevation) && _deepEquals(cornerRadius, other.cornerRadius);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DialogConfigDto(initialSelectedDate: $initialSelectedDate, locale: $locale, yearRangeStart: $yearRangeStart, yearRangeEnd: $yearRangeEnd, selectable: $selectable, showModeToggle: $showModeToggle, showTodayButton: $showTodayButton, showEnglishDate: $showEnglishDate, englishDateLocale: $englishDateLocale, initialCalendarSystemEra: $initialCalendarSystemEra, showCalendarSystemToggle: $showCalendarSystemToggle, showAdjacentMonthDays: $showAdjacentMonthDays, eventOptions: $eventOptions, title: $title, confirmText: $confirmText, dismissText: $dismissText, tonalElevation: $tonalElevation, cornerRadius: $cornerRadius)';
  }
}

/// One marked event for the pickers: an [EventDto] plus how to draw it.
class EventMarkDto {
  EventMarkDto({
    required this.year,
    required this.month,
    required this.dayOfMonth,
    required this.name,
    required this.kind,
    required this.closesOffices,
    required this.colorArgb,
    required this.indicate,
  });

  int year;

  int month;

  int dayOfMonth;

  String name;

  EventKindDto kind;

  bool closesOffices;

  int colorArgb;

  bool indicate;

  List<Object?> _toList() {
    return <Object?>[
      year,
      month,
      dayOfMonth,
      name,
      kind,
      closesOffices,
      colorArgb,
      indicate,
    ];
  }

  Object encode() {
    return _toList();  }

  static EventMarkDto decode(Object result) {
    result as List<Object?>;
    return EventMarkDto(
      year: result[0]! as int,
      month: result[1]! as int,
      dayOfMonth: result[2]! as int,
      name: result[3]! as String,
      kind: result[4]! as EventKindDto,
      closesOffices: result[5]! as bool,
      colorArgb: result[6]! as int,
      indicate: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EventMarkDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(year, other.year) && _deepEquals(month, other.month) && _deepEquals(dayOfMonth, other.dayOfMonth) && _deepEquals(name, other.name) && _deepEquals(kind, other.kind) && _deepEquals(closesOffices, other.closesOffices) && _deepEquals(colorArgb, other.colorArgb) && _deepEquals(indicate, other.indicate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EventMarkDto(year: $year, month: $month, dayOfMonth: $dayOfMonth, name: $name, kind: $kind, closesOffices: $closesOffices, colorArgb: $colorArgb, indicate: $indicate)';
  }
}

/// What the pickers should mark; mirrors the platform event option bags.
class EventOptionsDto {
  EventOptionsDto({
    required this.weeklyOffDays,
    required this.events,
    required this.markWeeklyOff,
    required this.markEvents,
    required this.tintContainer,
    required this.indicateWeeklyOff,
    required this.describeEvents,
    required this.weeklyOffColorArgb,
    required this.publicHolidayColorArgb,
    required this.religiousColorArgb,
    required this.regionalColorArgb,
    required this.observanceColorArgb,
    required this.markedContainerColorArgb,
  });

  List<int> weeklyOffDays;

  List<EventMarkDto> events;

  bool markWeeklyOff;

  bool markEvents;

  bool tintContainer;

  bool indicateWeeklyOff;

  bool describeEvents;

  int weeklyOffColorArgb;

  int publicHolidayColorArgb;

  int religiousColorArgb;

  int regionalColorArgb;

  int observanceColorArgb;

  int markedContainerColorArgb;

  List<Object?> _toList() {
    return <Object?>[
      weeklyOffDays,
      events,
      markWeeklyOff,
      markEvents,
      tintContainer,
      indicateWeeklyOff,
      describeEvents,
      weeklyOffColorArgb,
      publicHolidayColorArgb,
      religiousColorArgb,
      regionalColorArgb,
      observanceColorArgb,
      markedContainerColorArgb,
    ];
  }

  Object encode() {
    return _toList();  }

  static EventOptionsDto decode(Object result) {
    result as List<Object?>;
    return EventOptionsDto(
      weeklyOffDays: (result[0]! as List<Object?>).cast<int>(),
      events: (result[1]! as List<Object?>).cast<EventMarkDto>(),
      markWeeklyOff: result[2]! as bool,
      markEvents: result[3]! as bool,
      tintContainer: result[4]! as bool,
      indicateWeeklyOff: result[5]! as bool,
      describeEvents: result[6]! as bool,
      weeklyOffColorArgb: result[7]! as int,
      publicHolidayColorArgb: result[8]! as int,
      religiousColorArgb: result[9]! as int,
      regionalColorArgb: result[10]! as int,
      observanceColorArgb: result[11]! as int,
      markedContainerColorArgb: result[12]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EventOptionsDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(weeklyOffDays, other.weeklyOffDays) && _deepEquals(events, other.events) && _deepEquals(markWeeklyOff, other.markWeeklyOff) && _deepEquals(markEvents, other.markEvents) && _deepEquals(tintContainer, other.tintContainer) && _deepEquals(indicateWeeklyOff, other.indicateWeeklyOff) && _deepEquals(describeEvents, other.describeEvents) && _deepEquals(weeklyOffColorArgb, other.weeklyOffColorArgb) && _deepEquals(publicHolidayColorArgb, other.publicHolidayColorArgb) && _deepEquals(religiousColorArgb, other.religiousColorArgb) && _deepEquals(regionalColorArgb, other.regionalColorArgb) && _deepEquals(observanceColorArgb, other.observanceColorArgb) && _deepEquals(markedContainerColorArgb, other.markedContainerColorArgb);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EventOptionsDto(weeklyOffDays: $weeklyOffDays, events: $events, markWeeklyOff: $markWeeklyOff, markEvents: $markEvents, tintContainer: $tintContainer, indicateWeeklyOff: $indicateWeeklyOff, describeEvents: $describeEvents, weeklyOffColorArgb: $weeklyOffColorArgb, publicHolidayColorArgb: $publicHolidayColorArgb, religiousColorArgb: $religiousColorArgb, regionalColorArgb: $regionalColorArgb, observanceColorArgb: $observanceColorArgb, markedContainerColorArgb: $markedContainerColorArgb)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LangDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NameFormatDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is DateFormatStyleDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is DigitScriptDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is EventKindDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is DatePatternDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is BrightnessDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is DateDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is TimeDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is CalendarDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is MonthInfoDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is DateTimeDto) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is YearRangeDto) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is LocaleDto) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is EventDto) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is PolicyDto) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is DayStatusDto) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is SelectableDto) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is AppearanceDto) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is DialogConfigDto) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is EventMarkDto) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is EventOptionsDto) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : LangDto.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : NameFormatDto.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : DateFormatStyleDto.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : DigitScriptDto.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : EventKindDto.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : DatePatternDto.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : BrightnessDto.values[value];
      case 136:
        return DateDto.decode(readValue(buffer)!);
      case 137:
        return TimeDto.decode(readValue(buffer)!);
      case 138:
        return CalendarDto.decode(readValue(buffer)!);
      case 139:
        return MonthInfoDto.decode(readValue(buffer)!);
      case 140:
        return DateTimeDto.decode(readValue(buffer)!);
      case 141:
        return YearRangeDto.decode(readValue(buffer)!);
      case 142:
        return LocaleDto.decode(readValue(buffer)!);
      case 143:
        return EventDto.decode(readValue(buffer)!);
      case 144:
        return PolicyDto.decode(readValue(buffer)!);
      case 145:
        return DayStatusDto.decode(readValue(buffer)!);
      case 146:
        return SelectableDto.decode(readValue(buffer)!);
      case 147:
        return AppearanceDto.decode(readValue(buffer)!);
      case 148:
        return DialogConfigDto.decode(readValue(buffer)!);
      case 149:
        return EventMarkDto.decode(readValue(buffer)!);
      case 150:
        return EventOptionsDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The synchronous conversion engine. Every method delegates to the compiled
/// Kotlin `:core` module; failures surface as platform errors with the
/// Kotlin exception message.
class EngineApi {
  /// Constructor for [EngineApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EngineApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<YearRangeDto> getBsYearRange() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getBsYearRange$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as YearRangeDto;
  }

  Future<YearRangeDto> getAdYearRange() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getAdYearRange$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as YearRangeDto;
  }

  Future<YearRangeDto> getAdYearRangeForBsYears(int first, int last) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getAdYearRangeForBsYears$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[first, last]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as YearRangeDto;
  }

  Future<CalendarDto> getTodayBs() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getTodayBs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<CalendarDto> getTodayAd() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getTodayAd$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<TimeDto> getCurrentTime() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getCurrentTime$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as TimeDto;
  }

  Future<CalendarDto> convertAdToBs(int year, int month, int dayOfMonth) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.convertAdToBs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month, dayOfMonth]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<CalendarDto> convertBsToAd(int year, int month, int dayOfMonth) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.convertBsToAd$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month, dayOfMonth]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<CalendarDto> getBsCalendar(int year, int month, int dayOfMonth) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getBsCalendar$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month, dayOfMonth]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<CalendarDto> getAdCalendar(int year, int month, int dayOfMonth) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getAdCalendar$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month, dayOfMonth]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<bool> isAdDateConvertible(int year, int month, int dayOfMonth) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.isAdDateConvertible$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month, dayOfMonth]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<MonthInfoDto> getBsMonth(int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getBsMonth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MonthInfoDto;
  }

  Future<MonthInfoDto> getAdMonth(int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getAdMonth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MonthInfoDto;
  }

  Future<List<CalendarDto?>> getBsCalendarsInAdMonth(int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getBsCalendarsInAdMonth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CalendarDto?>();
  }

  Future<List<CalendarDto>> getAdCalendarsInBsMonth(int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getAdCalendarsInBsMonth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CalendarDto>();
  }

  Future<int> getTotalDaysInBsMonth(int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getTotalDaysInBsMonth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<int> getTotalDaysInAdMonth(int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getTotalDaysInAdMonth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<CalendarDto> addDaysToBsDate(int year, int month, int dayOfMonth, int days) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.addDaysToBsDate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[year, month, dayOfMonth, days]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<int> getBsDaysBetween(DateDto start, DateDto end) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getBsDaysBetween$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[start, end]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<int> getAdDaysBetween(DateDto start, DateDto end) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getAdDaysBetween$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[start, end]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<int> compareBsDates(DateDto from, DateDto to) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.compareBsDates$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[from, to]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<String> getWeekdayName(int dayOfWeek, NameFormatDto format, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getWeekdayName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[dayOfWeek, format, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> getBsMonthName(int month, NameFormatDto format, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getBsMonthName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[month, format, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> getAdMonthName(int month, NameFormatDto format, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.getAdMonthName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[month, format, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatBsDate(CalendarDto calendar, LocaleDto locale) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatBsDate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[calendar, locale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatAdDate(CalendarDto calendar, LocaleDto locale) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatAdDate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[calendar, locale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatBsDateByPattern(String pattern, DateDto date, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatBsDateByPattern$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pattern, date, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatAdDateByPattern(String pattern, DateDto date, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatAdDateByPattern$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pattern, date, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatTimeByPattern(String pattern, TimeDto time, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatTimeByPattern$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pattern, time, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatBsDateTimeByPattern(String pattern, DateDto date, TimeDto? time, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatBsDateTimeByPattern$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pattern, date, time, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatAdDateTimeByPattern(String pattern, DateDto date, TimeDto? time, LangDto language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatAdDateTimeByPattern$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pattern, date, time, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatTimeEnglish(TimeDto time, bool use12HourFormat) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatTimeEnglish$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[time, use12HourFormat]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> formatTimeNepali(TimeDto time, bool use12HourFormat) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.formatTimeNepali$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[time, use12HourFormat]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> bsDateTimeToIso(DateDto date, TimeDto time) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.bsDateTimeToIso$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[date, time]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> adDateTimeToIso(DateDto date, TimeDto time) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.adDateTimeToIso$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[date, time]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<DateTimeDto> bsDateTimeFromIso(String isoDateTime) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.bsDateTimeFromIso$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[isoDateTime]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DateTimeDto;
  }

  Future<DateTimeDto> adDateTimeFromIso(String isoDateTime) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.adDateTimeFromIso$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[isoDateTime]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DateTimeDto;
  }

  Future<String> localizeDigits(String text, DigitScriptDto script) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.localizeDigits$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text, script]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> toLatinDigits(String text) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.toLatinDigits$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<String> wireFormatDate(DateDto date, DatePatternDto pattern, DigitScriptDto script) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.wireFormatDate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[date, pattern, script]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<DateDto?> wireParseDate(String input, DatePatternDto pattern) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.wireParseDate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[input, pattern]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as DateDto?;
  }

  Future<String> wireFormatTime(TimeDto time) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.wireFormatTime$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[time]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<TimeDto?> wireParseTime(String input) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.wireParseTime$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[input]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as TimeDto?;
  }

  Future<DayStatusDto> statusOf(PolicyDto policy, DateDto date) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.statusOf$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, date]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DayStatusDto;
  }

  Future<List<DayStatusDto>> monthStatus(PolicyDto policy, int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.monthStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<DayStatusDto>();
  }

  Future<List<EventDto>> eventsOn(PolicyDto policy, DateDto date) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.eventsOn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, date]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<EventDto>();
  }

  Future<List<EventDto>> eventsIn(PolicyDto policy, int year, int month) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.eventsIn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, year, month]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<EventDto>();
  }

  Future<bool> isNonWorkingDay(PolicyDto policy, DateDto date) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.isNonWorkingDay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, date]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<int> workingDaysBetween(PolicyDto policy, DateDto start, DateDto end) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.workingDaysBetween$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, start, end]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<CalendarDto> nextWorkingDay(PolicyDto policy, DateDto from) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.nextWorkingDay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, from]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<CalendarDto> addWorkingDays(PolicyDto policy, DateDto from, int days) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.addWorkingDays$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy, from, days]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CalendarDto;
  }

  Future<List<EventDto>> eventSpanningDays(EventDto event, int days) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.eventSpanningDays$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[event, days]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<EventDto>();
  }

  Future<List<EventDto>> eventSpanningThrough(EventDto event, DateDto end) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.EngineApi.eventSpanningThrough$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[event, end]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<EventDto>();
  }
}

/// Native picker presentation and theming.
class PickerHostApi {
  /// Constructor for [PickerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PickerHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Presents the modal picker dialog and completes with the confirmed date,
  /// or null when it was dismissed.
  Future<CalendarDto?> showDatePickerDialog(DialogConfigDto config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.PickerHostApi.showDatePickerDialog$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as CalendarDto?;
  }

  /// Presents the full-screen picker dialog and completes with the confirmed
  /// date, or null when it was dismissed.
  Future<CalendarDto?> showFullScreenDatePickerDialog(DialogConfigDto config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.PickerHostApi.showFullScreenDatePickerDialog$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as CalendarDto?;
  }

  /// Applies the palette to every hosted picker, current and future.
  Future<void> applyAppearance(AppearanceDto appearance) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.PickerHostApi.applyAppearance$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[appearance]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Restores every appearance slot to Material's own value.
  Future<void> resetAppearance() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nepali_date_picker_kmp.PickerHostApi.resetAppearance$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Events flowing back from embedded picker views, keyed by the platform
/// view's id.
abstract class PickerViewFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onHeightChanged(int viewId, double height);

  void onDateSelected(int viewId, CalendarDto? date);

  void onRangeSelected(int viewId, CalendarDto? start, CalendarDto? end);

  void onValueChanged(int viewId, DateDto? value);

  void onRangeValueChanged(int viewId, DateDto? start, DateDto? end);

  void onCalendarSystemChanged(int viewId, int era);

  /// The event behind a tapped line of an embedded calendar's month list.
  void onEventTapped(int viewId, EventDto event);

  /// The month an embedded calendar moved to, in the calendar it displays.
  void onDisplayedMonthChanged(int viewId, int year, int month, int era);

  static void setUp(PickerViewFlutterApi? api, {
    BinaryMessenger? binaryMessenger, 
    String messageChannelSuffix = '',
  }) 
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onHeightChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final double arg_height = args[1]! as double;
          try {
            api.onHeightChanged(arg_viewId, arg_height);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onDateSelected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final CalendarDto? arg_date = args[1] as CalendarDto?;
          try {
            api.onDateSelected(arg_viewId, arg_date);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onRangeSelected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final CalendarDto? arg_start = args[1] as CalendarDto?;
          final CalendarDto? arg_end = args[2] as CalendarDto?;
          try {
            api.onRangeSelected(arg_viewId, arg_start, arg_end);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onValueChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final DateDto? arg_value = args[1] as DateDto?;
          try {
            api.onValueChanged(arg_viewId, arg_value);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onRangeValueChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final DateDto? arg_start = args[1] as DateDto?;
          final DateDto? arg_end = args[2] as DateDto?;
          try {
            api.onRangeValueChanged(arg_viewId, arg_start, arg_end);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onCalendarSystemChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final int arg_era = args[1]! as int;
          try {
            api.onCalendarSystemChanged(arg_viewId, arg_era);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onEventTapped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final EventDto arg_event = args[1]! as EventDto;
          try {
            api.onEventTapped(arg_viewId, arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nepali_date_picker_kmp.PickerViewFlutterApi.onDisplayedMonthChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final int arg_year = args[1]! as int;
          final int arg_month = args[2]! as int;
          final int arg_era = args[3]! as int;
          try {
            api.onDisplayedMonthChanged(arg_viewId, arg_year, arg_month, arg_era);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
